name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  deployments: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true
 
    - name: Setup local Conan index
      run: >
        git clone https://github.com/4J-company/conan-center-index.git &&
        conan remote add 4J-company ./conan-center-index --type local-recipes-index

    - name: Build
      run: >
        conan build .
        -b missing
        -o '&:target=benchmark'
        -s compiler.cppstd=23
        -s build_type=${{env.BUILD_TYPE}}
    
    - name: Run benchmark
      run: ./build/Release/bench/mr-math-bench --benchmark_format=json | tee benchmark_result.json

    - name: Download previous results
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1.18.0
      with:
        tool: 'googlecpp'
        output-file-path: benchmark_result.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '120%'
        comment-on-alert: true
        fail-on-alert: true
        alert-comment-cc-users: '@cone-forest'
